laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('marcas', 'MarcasController@index')->name('marcas');

    Route::get('produtos/tipo/{tipo_slug}/{codigo?}', 'ProdutosController@tipo')->name('produtos.tipo');
    Route::get('produtos/busca', 'ProdutosController@busca')->name('produtos.busca');

    Route::post('blog/comentario/{blog_post_slug}', 'BlogController@comentario')->name('blog.comentario');
	Route::get('blog/post/{blog_post_slug?}', 'BlogController@show')->name('blog.show');
	Route::get('blog/tag/{blog_tag_slug?}', 'BlogController@tag')->name('blog.tag');
	Route::get('blog/ano/{ano}/{mes?}', 'BlogController@data')->name('blog.data');
	Route::get('blog/{blog_categoria_slug?}', 'BlogController@index')->name('blog');

    Route::get('perfil', 'PerfilController@index')->name('perfil');
    Route::get('designers', 'DesignersController@index')->name('designers');
    Route::get('designers/{designer_slug}', 'DesignersController@show')->name('designers.show');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');

    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Localização
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if (in_array($idioma, ['pt', 'en'])) {
            Session::put('locale', $idioma);
        }
        return redirect()->intended();
    })->name('lang');

    // Area Profissional
    Route::group([
        'prefix' => 'area-profissional',
        'namespace' => 'AreaProfissional'
    ], function() {
        Route::group(['namespace' => 'Auth'], function() {
            Route::get('login', 'AuthController@showLoginForm')
                ->name('area-profissional.login');
            Route::post('login', 'AuthController@login')
                ->name('area-profissional.auth');
            Route::get('cadastro', 'AuthController@showRegisterForm')
                ->name('area-profissional.register');
            Route::post('cadastro', 'AuthController@register')
                ->name('area-profissional.register.post');
            Route::get('logout', 'AuthController@logout')
                ->name('area-profissional.logout');
            Route::get('esqueci-minha-senha', 'PasswordController@forgotPassword')
                ->name('area-profissional.reset');
            Route::post('redefinicao-de-senha', 'PasswordController@sendResetLinkEmail')
                ->name('area-profissional.reset.email');
            Route::get('redefinicao-de-senha/{token}', 'PasswordController@showResetForm')
                ->name('area-profissional.reset.token');
            Route::post('redefinir-senha', 'PasswordController@reset')
                ->name('area-profissional.reset.post');
        });

        Route::group(['middleware' => ['auth.profissional']], function() {
            Route::get('/', function() {
                return view('frontend.area-profissional.home', [
                    'home' => \App\Models\AreaProfissional\TelaInicial::first()
                ]);
            })->name('area-profissional');

            Route::get('meu-cadastro', 'MeuCadastroController@index')->name('area-profissional.meu-cadastro');
            Route::patch('meu-cadastro', 'MeuCadastroController@update')->name('area-profissional.meu-cadastro.update');

            Route::get('orcamento', 'OrcamentoController@index')
                ->name('area-profissional.orcamento');
            Route::post('orcamento', 'OrcamentoController@post')
                ->name('area-profissional.orcamento.post');
            Route::get('orcamento/historico/{id?}', 'OrcamentoController@history')
                ->name('area-profissional.orcamento.historico');
            Route::post('orcamento/{id}', 'OrcamentoController@add')
                ->name('area-profissional.orcamento.adicionar');
            Route::get('orcamento/{id}/remover', 'OrcamentoController@remove')
                ->name('area-profissional.orcamento.remover');

            Route::get('relacionamento', 'RelacionamentoController@index')
                ->name('area-profissional.relacionamento');
            Route::get('relacionamento/regulamento', 'RelacionamentoController@regulamento')
                ->name('area-profissional.relacionamento.regulamento');
            Route::get('relacionamento/extrato', 'RelacionamentoController@extrato')
                ->name('area-profissional.relacionamento.extrato');
        });
    });

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('enderecos', 'EnderecosController');
		Route::get('produtos', 'ProdutosController@all')->name('painel.produtos.all'); // todos os produtos
        Route::post('produtos/imagens/upload', 'ProdutosImagensController@upload')
            ->name('painel.produtos.imagens.upload');
		Route::resource('fornecedores', 'FornecedoresController');
		Route::resource('fornecedores.linhas', 'LinhasController');
		Route::resource('fornecedores.linhas.produtos', 'ProdutosController'); // crud produtos
		Route::get('fornecedores/{fornecedores}/linhas/{linhas}/produtos/{produtos}/imagens/clear', [
			'as'   => 'painel.fornecedores.linhas.produtos.imagens.clear',
			'uses' => 'ProdutosImagensController@clear'
		]);
		Route::resource('fornecedores.linhas.produtos.imagens', 'ProdutosImagensController', ['parameters' => ['imagens' => 'imagens_produtos']]);
		Route::resource('produtos-materiais', 'ProdutosMateriaisController');
        Route::resource('tipos', 'TiposController');

		Route::resource('chamadas', 'ChamadasController');
		Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
		Route::resource('banners', 'BannersController');
		Route::resource('marcas', 'MarcasController');
		Route::resource('perfil', 'PerfilController', ['only' => ['index', 'update']]);
		Route::resource('designers-frase', 'DesignersFraseController', ['only' => ['index', 'update']]);
		Route::resource('designers', 'DesignersController');
		Route::get('designers/{designers}/imagens/clear', [
			'as'   => 'painel.designers.imagens.clear',
			'uses' => 'DesignersImagensController@clear'
		]);
        Route::resource('designers.imagens', 'DesignersImagensController', ['parameters' => ['imagens' => 'imagens_designers']]);

        Route::resource('blog/categorias', 'BlogCategoriasController', ['parameters' => ['categorias' => 'categorias_blog']]);
        Route::resource('blog', 'BlogPostsController', ['parameters' => ['blog' => 'posts']]);
        Route::resource('blog.comentarios', 'BlogComentariosController', ['parameters' => ['blog' => 'posts'], ['only' => ['index', 'show', 'update']]]);

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');

        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');

        // Painel / Area Profissional
        Route::group([
            'prefix'    => 'area-profissional',
            'namespace' => 'AreaProfissional',
        ], function() {
            Route::resource('e-mail-avisos', 'EMailAvisosController', ['only' => ['index', 'update']]);
            Route::resource('imagem-de-capa', 'ImagemDeCapaController', ['only' => ['index', 'update']]);
            Route::get('usuarios/newsletter', 'UsuariosController@newsletter')->name('painel.area-profissional.usuarios.newsletter');
            Route::resource('tela-inicial', 'TelaInicialController', ['only' => ['index', 'update']]);
            Route::resource('usuarios', 'UsuariosController', ['only' => ['index', 'show', 'update', 'destroy'], 'parameters' => ['usuarios' => 'usuarios-catalogo']]);
            Route::resource('orcamentos', 'OrcamentosController', ['only' => ['index', 'show', 'destroy']]);
        });

        Route::resource('usuarios', 'UsuariosController');
		Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');

        // internacional
		Route::resource('internacional/banners', 'IntBannersController', ['only' => ['index', 'create', 'store']]);
        Route::get('internacional/banners/{id}/edit', 'IntBannersController@edit')->name('painel.internacional.banners.edit');
        Route::patch('internacional/banners/{id}/update', 'IntBannersController@update')->name('painel.internacional.banners.update');
        Route::delete('internacional/banners/{id}/destroy', 'IntBannersController@destroy')->name('painel.internacional.banners.destroy');
        Route::resource('internacional/home', 'IntHomeController', ['only' => ['index', 'update']]);
        Route::resource('internacional/perfil', 'IntPerfilController', ['only' => ['index', 'update']]);
        Route::resource('internacional/contato', 'IntContatoController', ['only' => ['index', 'update']]);

laravel/app/Models/AreaProfissional/Orcamento.php
<?php

namespace App\Models\AreaProfissional;

use Illuminate\Database\Eloquent\Model;

use App\Models\Produto;

class Orcamento extends Model
{
    protected $table = 'orcamentos';

    protected $guarded = ['id'];

    public function usuario()
    {
        return $this->belongsTo(Usuario::class, 'usuario_id');
    }

    public function getDataAttribute()
    {
        return $this->created_at->format('d/m/Y - H:i');
    }

    public function getItensAttribute()
    {
        $itens = collect(json_decode($this->orcamento));

        $produtosIds = $itens->map(function($item) {
            return $item->id;
        });

        $produtos = Produto::with('tipo')->whereIn('id', $produtosIds)->get();

        return $itens->map(function($item) use ($produtos) {
            $item->quantidade = property_exists($item, 'quantidade') ? $item->quantidade : 1;
            $item->produto = $produtos->first(function($index, $produto) use ($item) {
                return $produto->id == $item->id;
            });

            return $item;
        });
    }

    public function getItensCountAttribute()
    {
        return count(json_decode($this->orcamento, true));
    }
}

laravel/app/Http/Controllers/AreaProfissional/MeuCadastroController.php
<?php

namespace App\Http\Controllers\AreaProfissional;

use App\Http\Controllers\Controller;
use App\Http\Requests\AreaProfissional\CadastroRequest;

class MeuCadastroController extends Controller
{
    public function index()
    {
        $user = auth('profissional')->user();

        return view('frontend.area-profissional.meu-cadastro', compact('user'));
    }

    public function update(CadastroRequest $request)
    {
        try {

            $user = auth('profissional')->user();

            $input = $request->only([
                'nome',
                'email',
                'cpf',
                'telefone',
                'empresa',
                'cargo',
                'pais',
                'cep',
                'endereco',
                'numero',
                'complemento',
                'cidade',
                'estado',
                'password',
                'receber_newsletter'
            ]);

            if (isset($input['password']) && strlen($input['password'])) {
                $input['password'] = bcrypt($input['password']);
            } else {
                unset($input['password']);
            }

            $user->update($input);

            return back()->with('success', t('profissional.cadastro-alterado'));

        } catch (\Exception $e) {

            return back()->withErrors([t('profissional.cadastro-erro')]);

        }
    }
}

laravel/app/Http/Controllers/AreaProfissional/OrcamentoController.php
<?php

namespace App\Http\Controllers\AreaProfissional;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;

use App\Http\Requests\AreaProfissional\OrcamentoRequest;
use App\Models\AreaProfissional\EMailAvisos;
use App\Models\AreaProfissional\Orcamento;
use App\Models\Produto;

class OrcamentoController extends Controller
{
    private $orcamento;

    public function __construct()
    {
        if (! auth('profissional')->user()->podeSolicitarOrcamento) {
            return redirect()->route('home')->send();
        }

        $this->orcamento = session()->get('orcamento', []);
    }

    public function index()
    {
        $itens = $this->getItens();

        return view('frontend.area-profissional.orcamento.index', compact('itens'));
    }

    public function post(OrcamentoRequest $request)
    {
        try {

            $itens = $this->getItens();

            $quantidades = $request->get('quantidade');
            $observacoes = $request->get('observacoes');

            $orcamento = Orcamento::create([
                'usuario_id'  => auth('profissional')->user()->id,
                'observacoes' => $observacoes,
                'orcamento'   => json_encode($itens->map(
                    function($item, $index) use ($quantidades, $observacoes) {
                        return [
                            'id'         => $item->id,
                            'codigo'     => $item->codigo,
                            'divisao'    => $item->divisao,
                            'imagem'     => $item->imagem_capa,
                            'quantidade' => (int) $quantidades[$index],
                        ];
                    })
                ),
            ]);

            session()->put('orcamento', []);

            try {
                $email = EMailAvisos::firstOrFail()->email;

                if ($email) {
                    Mail::send('emails.area-profissional.orcamento', compact('orcamento'), function($m) use ($email) {
                        $m->to($email, config('app.name'))
                        ->subject('[ORÇAMENTO] '.config('app.name'));
                    });
                }
            } catch (\Exception $e) {}

            return redirect()->route('area-profissional.orcamento')->with('enviado', true);

        } catch (\Exception $e) {

            return back()->withErrors([t('profissional.orcamento-erro')]);

        }
    }

    public function history($id = null)
    {
        $user = auth('profissional')->user();

        if ($id) {
            $orcamentoHistorico = Orcamento::where([
                'id'         => $id,
                'usuario_id' => $user->id,
            ])->firstOrFail();

            return view('frontend.area-profissional.orcamento.show', compact('orcamentoHistorico'));
        }

        $orcamentos = Orcamento::where('usuario_id', $user->id)->orderBy('created_at', 'DESC')->get();

        return view('frontend.area-profissional.orcamento.historico', compact('orcamentos'));
    }

    public function add($id)
    {
        $produto = Produto::find($id);

        if (! $produto) {
            return response()->json('Produto não encontrado.', 500);
        }

        if (! in_array($produto->id, $this->orcamento)) {
            $this->orcamento[] = $produto->id;
            session()->put('orcamento', $this->orcamento);
        }

        return $this->orcamento;
    }

    public function remove($id)
    {
        if (in_array($id, $this->orcamento)) {
            session()->put('orcamento', array_diff($this->orcamento, [$id]));
        }

        return redirect()->route('area-profissional.orcamento');
    }

    protected function getItens()
    {
        $produtos = Produto::with('tipo')
            ->whereIn('id', $this->orcamento)
            ->get();

        return collect($this->orcamento)
            ->map(function($id) use ($produtos) {
                return $produtos->first(function($index, $produto) use ($id) {
                    return $produto->id == $id;
                });
            })->filter(function($item) {
                return !!$item;
            });
    }
}

laravel/app/Http/Controllers/Painel/AreaProfissional/EMailAvisosController.php
<?php

namespace App\Http\Controllers\Painel\AreaProfissional;

use Illuminate\Http\Request;

use App\Http\Requests\AreaProfissional\EMailAvisosRequest;
use App\Http\Controllers\Controller;

use App\Models\AreaProfissional\EMailAvisos;

class EMailAvisosController extends Controller
{
    public function index()
    {
        $registro = EMailAvisos::first();

        return view('painel.area-profissional.e-mail-avisos.edit', compact('registro'));
    }

    public function update(EMailAvisosRequest $request, EMailAvisos $registro)
    {
        try {
            $input = $request->all();


            $registro->update($input);

            return redirect()->route('painel.area-profissional.e-mail-avisos.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/resources/views/frontend/area-profissional/orcamento/historico.blade.php
@extends('frontend.common.template')

@section('content')

    <div class="area-profissional">
        <div class="center">
            <aside>
                <h2>{{ t('nav.catalogo') }}</h2>
                @include('frontend.area-profissional._nav')
            </aside>

            <main class="orcamento">
                <div>
                    @if(count($orcamentos))
                    <div class="orcamento-pedido">
                        <p>{{ t('profissional.historico') }}</p>

                        <div class="orcamento-lista">
                            @foreach($orcamentos as $orcamento)
                            <div class="orcamento-item">
                                <div>
                                    {{ $orcamento->created_at->format('d/m/Y') }}
                                    &middot;
                                    {{ $orcamento->itens_count }}
                                    {{ $orcamento->itens_count > 1 ? 'itens' : 'item' }}
                                </div>
                                <a href="{{ route('area-profissional.orcamento.historico', $orcamento->id) }}" class="btn-visualizar">
                                    {{ t('profissional.visualizar') }}
                                </a>
                            </div>
                            @endforeach
                        </div>
                    </div>
                    @else
                    <div class="orcamento-vazio">
                        {!! t('profissional.historico-vazio') !!}
                    </div>
                    @endif
                </div>
            </main>
        </div>
    </div>

@endsection

laravel/resources/views/frontend/area-profissional/orcamento/index.blade.php
@extends('frontend.common.template')

@section('content')

    <div class="area-profissional">
        <div class="center">
            <aside>
                <h2>{{ t('nav.catalogo') }}</h2>
                @include('frontend.area-profissional._nav')
            </aside>

            <main class="orcamento">
                <div>
                    @if(session('enviado'))
                        <div class="flash flash-success">{{ t('profissional.orcamento-enviado') }}</div>
                    @endif
                    @if($errors->any())
                        <div class="flash flash-error">
                            @foreach($errors->all() as $error)
                            {!! $error !!}<br>
                            @endforeach
                        </div>
                    @endif

                    @if(count($orcamento))
                    <div class="orcamento-pedido">
                        <p>{{ t('profissional.pedido-orcamento') }}</p>

                        <form action="{{ route('area-profissional.orcamento.post') }}" method="POST">
                            {!! csrf_field() !!}

                            <div class="orcamento-lista">
                                @foreach($itens as $key => $item)
                                <div class="orcamento-item">
                                    <a href="{{ route('produtos.tipo', [$item->tipo->slug, $item->codigo]) }}">
                                        <img src="{{ prod_url('assets/img/produtos/capas/'.$item->imagem_capa) }}">
                                    </a>
                                    <div>
                                        {{ $item->codigo }}
                                        @foreach(explode(',', $item->divisao) as $divisao)
                                            <span>{{ t('nav.'.$divisao) }}</span>
                                        @endforeach
                                    </div>
                                    <div class="input-quantidade">
                                        <input type="number" name="quantidade[]" value="{{ old('quantidade.'.$key) ?: '1' }}" min="1" required>
                                    </div>
                                    <a href="{{ route('area-profissional.orcamento.remover', $item->id) }}" class="btn-excluir">
                                        {{ t('profissional.excluir') }}
                                    </a>
                                </div>
                                @endforeach
                            </div>

                            <textarea name="observacoes" placeholder="{{ t('profissional.observacoes') }}">{{ old('observacoes') }}</textarea>

                            <input type="submit" class="orcamento-btn" value="{{ t('profissional.enviar-pedido') }}">
                        </form>
                    </div>
                    @else
                    <div class="orcamento-vazio">
                        {!! t('profissional.orcamento-vazio') !!}
                    </div>
                    @endif
                </div>
            </main>
        </div>
    </div>

@endsection

laravel/resources/views/frontend/area-profissional/orcamento/show.blade.php
@extends('frontend.common.template')

@section('content')

    <div class="area-profissional">
        <div class="center">
            <aside>
                <h2>{{ t('nav.catalogo') }}</h2>
                @include('frontend.area-profissional._nav')
            </aside>

            <main class="orcamento">
                <div class="orcamento-pedido">
                    <p>
                        {{ t('profissional.enviado-em') }}
                        <strong>{{ $orcamentoHistorico->created_at->format('d/m/Y') }}</strong>
                    </p>

                    <div class="orcamento-lista">
                        @foreach($orcamentoHistorico->itens as $item)
                        <div class="orcamento-item">
                            @if($item->produto)
                            <a href="{{ route('produtos.tipo', [$item->produto->tipo->slug, $item->produto->codigo]) }}">
                                <img src="{{ prod_url('assets/img/produtos/capas/'.$item->produto->imagem_capa) }}">
                            </a>
                            @else
                                <img src="{{ prod_url('assets/img/produtos/capas/'.$item->imagem) }}">
                            @endif
                            <div>
                                {{ $item->codigo }}
                                @foreach(explode(',', $item->divisao) as $divisao)
                                <span>{{ t('nav.'.$divisao) }}</span>
                                @endforeach
                            </div>
                            <div class="quantidade">{{ $item->quantidade }}</div>
                        </div>
                        @endforeach
                    </div>

                    @if($orcamentoHistorico->observacoes)
                        <div class="observacoes">
                            <small>{{ t('profissional.observacoes') }}</small>
                            {!! nl2br($orcamentoHistorico->observacoes) !!}
                        </div>
                    @endif

                    <a href="{{ route('area-profissional.orcamento.historico') }}" class="orcamento-btn">
                        {{ t('profissional.voltar') }}
                    </a>
                </div>
            </main>
        </div>
    </div>

@endsection