laravel/app/Http/routes.php
    Route::post('blog/comentario/{blog_post_slug}', 'BlogController@comentario')->name('blog.comentario');
	Route::get('blog/post/{blog_post_slug?}', 'BlogController@show')->name('blog.show');
	Route::get('blog/tag/{blog_tag_slug?}', 'BlogController@tag')->name('blog.tag');
	Route::get('blog/ano/{ano}/{mes?}', 'BlogController@data')->name('blog.data');
	Route::get('blog/{blog_categoria_slug?}', 'BlogController@index')->name('blog');

    Route::get('perfil', 'PerfilController@index')->name('perfil');
    Route::get('designers', 'DesignersController@index')->name('designers');
    Route::get('designers/{designer_slug}', 'DesignersController@show')->name('designers.show');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');

    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Localização
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if (in_array($idioma, ['pt', 'en'])) {
            Session::put('locale', $idioma);
        }
        return redirect()->intended();
    })->name('lang');

    // Area Profissional
    Route::group([
        'prefix' => 'area-profissional',
        'namespace' => 'AreaProfissional'
    ], function() {
        Route::group(['namespace' => 'Auth'], function() {
            Route::get('login', 'AuthController@showLoginForm')
                ->name('area-profissional.login');
            Route::post('login', 'AuthController@login')
                ->name('area-profissional.auth');
            Route::get('cadastro', 'AuthController@showRegisterForm')
                ->name('area-profissional.register');
            Route::post('cadastro', 'AuthController@register')
                ->name('area-profissional.register.post');
            Route::get('logout', 'AuthController@logout')
                ->name('area-profissional.logout');
            Route::get('esqueci-minha-senha', 'PasswordController@forgotPassword')
                ->name('area-profissional.reset');
            Route::post('redefinicao-de-senha', 'PasswordController@sendResetLinkEmail')
                ->name('area-profissional.reset.email');
            Route::get('redefinicao-de-senha/{token}', 'PasswordController@showResetForm')
                ->name('area-profissional.reset.token');
            Route::post('redefinir-senha', 'PasswordController@reset')
                ->name('area-profissional.reset.post');
        });

        Route::group(['middleware' => ['auth.profissional']], function() {
            Route::get('/', function() {
                return view('frontend.area-profissional.home', [
                    'home' => \App\Models\AreaProfissional\TelaInicial::first()
                ]);
            })->name('area-profissional');

            Route::get('meu-cadastro', 'MeuCadastroController@index')->name('area-profissional.meu-cadastro');
            Route::patch('meu-cadastro', 'MeuCadastroController@update')->name('area-profissional.meu-cadastro.update');

            Route::get('orcamento', 'OrcamentoController@index')
                ->name('area-profissional.orcamento');
            Route::post('orcamento', 'OrcamentoController@post')
                ->name('area-profissional.orcamento.post');
            Route::get('orcamento/historico/{id?}', 'OrcamentoController@history')
                ->name('area-profissional.orcamento.historico');
            Route::post('orcamento/{id}', 'OrcamentoController@add')
                ->name('area-profissional.orcamento.adicionar');
            Route::get('orcamento/{id}/remover', 'OrcamentoController@remove')
                ->name('area-profissional.orcamento.remover');

            Route::get('relacionamento', 'RelacionamentoController@index')
                ->name('area-profissional.relacionamento');
            Route::get('relacionamento/regulamento', 'RelacionamentoController@regulamento')
                ->name('area-profissional.relacionamento.regulamento');
            Route::get('relacionamento/extrato', 'RelacionamentoController@extrato')
                ->name('area-profissional.relacionamento.extrato');
        });
    });

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('enderecos', 'EnderecosController');
		Route::get('produtos', 'ProdutosController@all')->name('painel.produtos.all'); // todos os produtos
        Route::post('produtos/imagens/upload', 'ProdutosImagensController@upload')
            ->name('painel.produtos.imagens.upload');
		Route::resource('fornecedores', 'FornecedoresController');
		Route::resource('fornecedores.linhas', 'LinhasController');
		Route::resource('fornecedores.linhas.produtos', 'ProdutosController'); // crud produtos
		Route::get('fornecedores/{fornecedores}/linhas/{linhas}/produtos/{produtos}/imagens/clear', [
			'as'   => 'painel.fornecedores.linhas.produtos.imagens.clear',
			'uses' => 'ProdutosImagensController@clear'
		]);
		Route::resource('fornecedores.linhas.produtos.imagens', 'ProdutosImagensController', ['parameters' => ['imagens' => 'imagens_produtos']]);
		Route::resource('produtos-materiais', 'ProdutosMateriaisController');
        Route::resource('tipos', 'TiposController');

		Route::resource('chamadas', 'ChamadasController');
		Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
		Route::resource('banners', 'BannersController');
		Route::resource('marcas', 'MarcasController');
		Route::resource('perfil', 'PerfilController', ['only' => ['index', 'update']]);
		Route::resource('designers-frase', 'DesignersFraseController', ['only' => ['index', 'update']]);
		Route::resource('designers', 'DesignersController');
		Route::get('designers/{designers}/imagens/clear', [
			'as'   => 'painel.designers.imagens.clear',
			'uses' => 'DesignersImagensController@clear'
		]);
        Route::resource('designers.imagens', 'DesignersImagensController', ['parameters' => ['imagens' => 'imagens_designers']]);

        Route::resource('blog/categorias', 'BlogCategoriasController', ['parameters' => ['categorias' => 'categorias_blog']]);
        Route::resource('blog', 'BlogPostsController', ['parameters' => ['blog' => 'posts']]);
        Route::resource('blog.comentarios', 'BlogComentariosController', ['parameters' => ['blog' => 'posts'], ['only' => ['index', 'show', 'update']]]);

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');

        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');

        // Painel / Area Profissional
        Route::group([
            'prefix'    => 'area-profissional',
            'namespace' => 'AreaProfissional',
        ], function() {
            Route::resource('e-mail-avisos', 'EMailAvisosController', ['only' => ['index', 'update']]);
            Route::resource('imagem-de-capa', 'ImagemDeCapaController', ['only' => ['index', 'update']]);
            Route::get('usuarios/newsletter', 'UsuariosController@newsletter')->name('painel.area-profissional.usuarios.newsletter');
            Route::resource('tela-inicial', 'TelaInicialController', ['only' => ['index', 'update']]);
            Route::resource('usuarios', 'UsuariosController', ['only' => ['index', 'show', 'update', 'destroy'], 'parameters' => ['usuarios' => 'usuarios-catalogo']]);
            Route::resource('orcamentos', 'OrcamentosController', ['only' => ['index', 'show', 'destroy']]);
        });

        Route::resource('usuarios', 'UsuariosController');
		Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');

        // internacional
		Route::resource('internacional/banners', 'IntBannersController', ['only' => ['index', 'create', 'store']]);
        Route::get('internacional/banners/{id}/edit', 'IntBannersController@edit')->name('painel.internacional.banners.edit');
        Route::patch('internacional/banners/{id}/update', 'IntBannersController@update')->name('painel.internacional.banners.update');
        Route::delete('internacional/banners/{id}/destroy', 'IntBannersController@destroy')->name('painel.internacional.banners.destroy');
        Route::resource('internacional/home', 'IntHomeController', ['only' => ['index', 'update']]);
        Route::resource('internacional/perfil', 'IntPerfilController', ['only' => ['index', 'update']]);
        Route::resource('internacional/contato', 'IntContatoController', ['only' => ['index', 'update']]);
		Route::resource('internacional/configuracoes', 'IntConfiguracoesController', ['only' => ['index', 'update']]);
    });

    // Painel / Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');

laravel/app/Http/Controllers/Painel/AceiteDeCookiesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\AceiteDeCookies;

class AceiteDeCookiesController extends Controller
{
    public function index()
    {
        $registros = AceiteDeCookies::orderBy('created_at', 'DESC')->get();

        return view('painel.cookies.index', compact('registros'));
    }
}

laravel/app/Http/Controllers/Painel/AreaProfissional/EMailAvisosController.php
<?php

namespace App\Http\Controllers\Painel\AreaProfissional;

use Illuminate\Http\Request;

use App\Http\Requests\AreaProfissional\EMailAvisosRequest;
use App\Http\Controllers\Controller;

use App\Models\AreaProfissional\EMailAvisos;

class EMailAvisosController extends Controller
{
    public function index()
    {
        $registro = EMailAvisos::first();

        return view('painel.area-profissional.e-mail-avisos.edit', compact('registro'));
    }

    public function update(EMailAvisosRequest $request, EMailAvisos $registro)
    {
        try {
            $input = $request->all();


            $registro->update($input);

            return redirect()->route('painel.area-profissional.e-mail-avisos.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/AreaProfissional/ImagemDeCapaController.php
<?php

namespace App\Http\Controllers\Painel\AreaProfissional;

use Illuminate\Http\Request;

use App\Http\Requests\AreaProfissional\ImagemDeCapaRequest;
use App\Http\Controllers\Controller;

use App\Models\AreaProfissional\ImagemDeCapa;

class ImagemDeCapaController extends Controller
{
    public function index()
    {
        $registro = ImagemDeCapa::first();

        return view('painel.area-profissional.imagem-de-capa.edit', compact('registro'));
    }

    public function update(ImagemDeCapaRequest $request, ImagemDeCapa $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = ImagemDeCapa::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.area-profissional.imagem-de-capa.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/AreaProfissional/OrcamentosController.php
<?php

namespace App\Http\Controllers\Painel\AreaProfissional;

use App\Http\Controllers\Controller;

use App\Models\AreaProfissional\Orcamento;

class OrcamentosController extends Controller
{
    public function index()
    {
        $orcamentos = Orcamento::with('usuario')
            ->orderBy('created_at', 'DESC')
            ->paginate(20);

        return view('painel.area-profissional.orcamentos.index', compact('orcamentos'));
    }

    public function show(Orcamento $orcamento)
    {
        return view('painel.area-profissional.orcamentos.show', compact('orcamento'));
    }

    public function destroy(Orcamento $orcamento)
    {
        try {

            $orcamento->delete();

            return back()->with('success', 'Orçamento excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir orçamento: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/AreaProfissional/TelaInicialController.php
<?php

namespace App\Http\Controllers\Painel\AreaProfissional;

use Illuminate\Http\Request;

use App\Http\Requests\AreaProfissional\TelaInicialRequest;
use App\Http\Controllers\Controller;

use App\Models\AreaProfissional\TelaInicial;

class TelaInicialController extends Controller
{
    public function index()
    {
        $registro = TelaInicial::first();

        return view('painel.area-profissional.tela-inicial.edit', compact('registro'));
    }

    public function update(TelaInicialRequest $request, TelaInicial $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = TelaInicial::upload_imagem();
            if (isset($input['imagem_en'])) $input['imagem_en'] = TelaInicial::upload_imagem_en();

            $registro->update($input);

            return redirect()->route('painel.area-profissional.tela-inicial.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/AreaProfissional/UsuariosController.php
<?php

namespace App\Http\Controllers\Painel\AreaProfissional;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use Maatwebsite\Excel\Facades\Excel;

use App\Models\AreaProfissional\Usuario;

class UsuariosController extends Controller
{
    public function index(Request $request)
    {
        if ($busca = $request->get('busca')) {
            $usuarios = Usuario::orderBy('nome', 'ASC')
                ->where('nome', 'LIKE', "%$busca%")
                ->orWhere('email', 'LIKE', "%$busca%")
                ->paginate(20);
        } else {
            $usuarios = Usuario::orderBy('nome', 'ASC')->paginate(20);
        }

        return view('painel.area-profissional.usuarios.index', compact('usuarios'));
    }

    public function show(Usuario $usuario)
    {
        return view('painel.area-profissional.usuarios.show', compact('usuario'));
    }

    public function update(Request $request, Usuario $usuario)
    {
        try {

            $input = $request->only(['is_funcionario', 'bloqueado']);

            $usuario->update($input);

            return redirect()->route('painel.area-profissional.usuarios.show', $usuario->id)->with('success', 'Usuário alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar usuário: '.$e->getMessage()]);

        }
    }

    public function destroy(Usuario $usuario)
    {
        try {

            $usuario->delete();

            return back()->with('success', 'Usuário excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir usuário: '.$e->getMessage()]);

        }
    }

    public function newsletter()
    {
        $registros = Usuario::where('receber_newsletter', 1)
            ->orderBy('nome', 'ASC')
            ->get([
                'nome',
                'email as e-mail',
            ]);

        $fileName = 'CasualMoveis-Newsletter_'.date('d-m-Y_His');

        Excel::create($fileName, function ($excel) use ($registros) {
            $excel->sheet('newsletter', function ($sheet) use ($registros) {
                $sheet->fromModel($registros);
            });
        })->download('csv');
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">{{ config('app.name') }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            @include('painel.common.nav')

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown @if(Tools::routeIs(['painel.usuarios*', 'painel.configuracoes*'])) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li @if(Tools::routeIs('painel.politica-de-privacidade*')) class="active" @endif>
                            <a href="{{ route('painel.politica-de-privacidade.index') }}" class="link-nav-painel">Política de Privacidade</a>
                        </li>
                        <li @if(Tools::routeIs('painel.aceite-de-cookies*')) class="active" @endif>
                            <a href="{{ route('painel.aceite-de-cookies') }}">Relatório de Cookies</a>
                        </li>
                        <li @if(Tools::routeIs('painel.configuracoes*')) class="active" @endif>
                            <a href="{{ route('painel.configuracoes.index') }}">Configurações</a>
                        </li>
                        <li @if(Tools::routeIs('painel.usuarios*')) class="active" @endif>
                            <a href="{{ route('painel.usuarios.index') }}">Usuários</a>
                        </li>
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
    <li class="dropdown @if(Tools::routeIs([
        'painel.banners*',
        'painel.home*',
        'painel.chamadas*',
        'painel.marcas*',
        'painel.perfil*',
        'painel.designers*',
    ])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Institucional
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.banners*')) class="active" @endif>
                <a href="{{ route('painel.banners.index') }}">Banners</a>
            </li>
            <li @if(Tools::routeIs('painel.home*')) class="active" @endif>
                <a href="{{ route('painel.home.index') }}">Home</a>
            </li>
            <li @if(Tools::routeIs('painel.chamadas*')) class="active" @endif>
                <a href="{{ route('painel.chamadas.index') }}">Chamadas</a>
            </li>
            <li class="divider"></li>
            <li @if(Tools::routeIs('painel.marcas*')) class="active" @endif>
                <a href="{{ route('painel.marcas.index') }}">Marcas</a>
            </li>
            <li @if(Tools::routeIs('painel.perfil*')) class="active" @endif>
                <a href="{{ route('painel.perfil.index') }}">Perfil</a>
            </li>
            <li @if(Tools::routeIs('painel.designers*')) class="active" @endif>
                <a href="{{ route('painel.designers.index') }}">Designers</a>
            </li>
        </ul>
    </li>
    <li class="dropdown @if(Tools::routeIs([
        'painel.fornecedores*',
        'painel.produtos*',
        'painel.tipos*',
        'painel.produtos-materiais*',
    ])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Catálogo
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.fornecedores*')) class="active" @endif>
                <a href="{{ route('painel.fornecedores.index') }}">Fornecedores</a>
            </li>
            <li @if(Tools::routeIs('painel.produtos.all')) class="active" @endif>
                <a href="{{ route('painel.produtos.all') }}">Todos os Produtos</a>
            </li>
            <li class="divider"></li>
            <li @if(Tools::routeIs('painel.tipos*')) class="active" @endif>
                <a href="{{ route('painel.tipos.index') }}">Tipos de Produtos</a>
            </li>
            <li @if(Tools::routeIs('painel.produtos-materiais*')) class="active" @endif>
                <a href="{{ route('painel.produtos-materiais.index') }}">Materiais de Produtos</a>
            </li>
        </ul>
    </li>
    <li @if(Tools::routeIs('painel.blog*')) class="active" @endif>
        <a href="{{ route('painel.blog.index') }}">Blog</a>
    </li>
    <li class="dropdown @if(Tools::routeIs(['painel.contato*', 'painel.enderecos*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.contato.index')) class="active" @endif>
                <a href="{{ route('painel.contato.index') }}">Informações de Contato</a>
            </li>
            <li @if(Tools::routeIs('painel.enderecos*')) class="active" @endif>
                <a href="{{ route('painel.enderecos.index') }}">Endereços</a>
            </li>
            <li @if(Tools::routeIs('painel.contato.recebidos*')) class="active" @endif>
                <a href="{{ route('painel.contato.recebidos.index') }}">
                    Contatos Recebidos
                    @if($contatosNaoLidos >= 1)
                    <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                    @endif
                </a>
            </li>
        </ul>
    </li>
    <li class="dropdown @if(Tools::routeIs([
        'painel.area-profissional.imagem-de-capa*',
        'painel.area-profissional.e-mail-avisos*',
        'painel.area-profissional.tela-inicial*',
        'painel.area-profissional.usuarios*',
        'painel.area-profissional.orcamentos*',
    ])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Área Profissional
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.area-profissional.imagem-de-capa*')) class="active" @endif>
                <a href="{{ route('painel.area-profissional.imagem-de-capa.index') }}">Imagem de Capa</a>
            </li>
            <li @if(Tools::routeIs('painel.area-profissional.e-mail-avisos*')) class="active" @endif>
                <a href="{{ route('painel.area-profissional.e-mail-avisos.index') }}">E-mail para Avisos</a>
            </li>
            <li @if(Tools::routeIs('painel.area-profissional.tela-inicial*')) class="active" @endif>
                <a href="{{ route('painel.area-profissional.tela-inicial.index') }}">Tela Inicial</a>
            </li>
            <li class="divider"></li>
            <li @if(Tools::routeIs('painel.area-profissional.usuarios*')) class="active" @endif>
                <a href="{{ route('painel.area-profissional.usuarios.index') }}">Usuários</a>
            </li>
            <li @if(Tools::routeIs('painel.area-profissional.orcamentos*')) class="active" @endif>
                <a href="{{ route('painel.area-profissional.orcamentos.index') }}">Orçamentos</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(Tools::routeIs([
        'painel.internacional.contato*',
        'painel.internacional.configuracoes*',
        'painel.internacional.banners*',
        'painel.internacional.home*',
        'painel.internacional.perfil*'
    ])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Internacional
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.internacional.contato.index')) class="active" @endif>
                <a href="{{ route('painel.internacional.contato.index') }}">Informações de Contato</a>
            </li>
            <li @if(Tools::routeIs('painel.internacional.configuracoes.index')) class="active" @endif>
                <a href="{{ route('painel.internacional.configuracoes.index') }}">Configurações</a>
            </li>
            <li @if(Tools::routeIs('painel.internacional.banners*')) class="active" @endif>
                <a href="{{ route('painel.internacional.banners.index') }}">Banners</a>
            </li>
            <li @if(Tools::routeIs('painel.internacional.home*')) class="active" @endif>
                <a href="{{ route('painel.internacional.home.index') }}">Home</a>
            </li>
            <li @if(Tools::routeIs('painel.internacional.perfil*')) class="active" @endif>
                <a href="{{ route('painel.internacional.perfil.index') }}">Perfil</a>
            </li>
        </ul>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('app.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/bootstrap-tagsinput/dist/bootstrap-tagsinput.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/bootstrap-tagsinput/dist/bootstrap-tagsinput-typeahead.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/vendor.painel.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/painel.css') }}">
</head>
<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="{{ asset('assets/vendor/jquery/dist/jquery.min.js') }}"><\/script>')</script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/vendor/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/typeahead.js/dist/typeahead.jquery.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/jquery-mask-plugin-master/dist/jquery.mask.min.js') }}"></script>
    <script src="{{ asset('assets/js/vendor.painel.js') }}"></script>
    <script src="{{ asset('assets/js/painel.js') }}"></script>
</body>
</html>